[mouse]
sensitivity_x = 0.3
sensitivity_y = 0.3

[bindings]
Move = { up = "W", down = "S", left = "A", right = "D" }
CaptureCursor = ["MouseLeft"]
Interact = ["E"]
Sprint = ["ShiftLeft"]
Examine = ["Q"]
Stash = ["T"]
CycleCarry = ["C"]
Drop = ["G"]
Place = ["R"]
ToggleJournal = ["J"]
Activate = ["F"]
Pause = ["Escape"]
