[[star_types]]
key = "red_dwarf"
luminosity_min = 0.01
luminosity_max = 0.08
temperature_min = 2500
temperature_max = 3700
mass_min = 0.08
mass_max = 0.45
weight = 7.0

[[star_types]]
key = "sun_like"
luminosity_min = 0.6
luminosity_max = 1.5
temperature_min = 5000
temperature_max = 6000
mass_min = 0.8
mass_max = 1.2
weight = 2.0

[[star_types]]
key = "blue_giant"
luminosity_min = 10.0
luminosity_max = 100.0
temperature_min = 10000
temperature_max = 30000
mass_min = 2.0
mass_max = 20.0
weight = 1.0
